name: Test and build
on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 14.x

    steps:
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/checkout@v2

      - name: Installing
        run: yarn --frozen-lockfile --perfer-offline --link-duplicates

      - name: Lint
        run: yarn lint

      - name: Unit tests
        run: yarn test --coverage --coverageReporters=lcov --coverageReporters=text-summary

      - name: Send test coverage to codecov
        continue-on-error: true
        uses: codecov/codecov-action@v1

      - name: Build
        run: yarn build

      - name: Archive dist components
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: dist/

  release:
    needs:
      - build
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - uses: actions/checkout@v2

      - name: Download dist from build job
        uses: actions/download-artifact@v2
        with:
          name: build
          path: dist

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/exec
            @semantic-release/git
        env:
          GIT_AUTHOR_EMAIL: ${{ secrets.SOCIALGROOVYBOT_EMAIL }}
          GIT_AUTHOR_NAME: ${{ secrets.SOCIALGROOVYBOT_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.SOCIALGROOVYBOT_EMAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.SOCIALGROOVYBOT_NAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.SOCIALGROOVYBOT_NPM_TOKEN }}
